FROM maven:3.6.3-jdk-11-slim AS build

ARG APPSETTING_COSMOS_DB
ARG APPSETTING_REDIS_PORT
ARG APPSETTING_REDIS_HOST
ARG APPSETTING_COSMOS_URL
ARG APPSETTING_COSMOS_KEY
ARG APPSETTING_REDIS_PASSWORD
ARG APPSETTING_DISCORD_BOT_TOKEN
ARG APPSETTING_NOTIFICATION_CHANNELS
ARG APPSETTING_SPINBOARD_SENDGRID_API_KEY
ARG APPSETTING_AUTH_TOKEN
ARG APPSETTING_ALEXA_NOTIFY_ME_TOKEN

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/ /app/src/
RUN mvn package -DskipTests -Denv.APPSETTING_COSMOS_DB=$APPSETTING_COSMOS_DB -Denv.APPSETTING_REDIS_PORT=$APPSETTING_REDIS_PORT -Denv.APPSETTING_REDIS_HOST=$APPSETTING_REDIS_HOST -Denv.APPSETTING_COSMOS_URL=$APPSETTING_COSMOS_URL -Denv.APPSETTING_COSMOS_KEY=$APPSETTING_COSMOS_KEY -Denv.APPSETTING_REDIS_PASSWORD=$APPSETTING_REDIS_PASSWORD -Denv.APPSETTING_DISCORD_BOT_TOKEN=$APPSETTING_DISCORD_BOT_TOKEN -Denv.APPSETTING_NOTIFICATION_CHANNELS=$APPSETTING_NOTIFICATION_CHANNELS -Denv.APPSETTING_SPINBOARD_SENDGRID_API_KEY=$APPSETTING_SPINBOARD_SENDGRID_API_KEY -Denv.APPSETTING_AUTH_TOKEN=$APPSETTING_AUTH_TOKEN -Denv.APPSETTING_ALEXA_NOTIFY_ME_TOKEN=$APPSETTING_ALEXA_NOTIFY_ME_TOKEN

FROM openjdk:11-jre-slim

COPY --from=build /app/target/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
