name: Build and push Docker image to Azure Container Registry
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JAR file
        run: ./mvnw package -DskipTests=true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/spinboard-java-main:${{ github.sha }}
          build-args: |
            APPSETTING_COSMOS_DB: ${{secrets.APPSETTING_COSMOS_DB}}
            APPSETTING_REDIS_PORT: ${{secrets.APPSETTING_REDIS_PORT}}
            APPSETTING_REDIS_HOST: ${{secrets.APPSETTING_REDIS_HOST}}
            APPSETTING_COSMOS_URL: ${{secrets.APPSETTING_COSMOS_URL}}
            APPSETTING_COSMOS_KEY: ${{secrets.APPSETTING_COSMOS_KEY}}
            APPSETTING_REDIS_PASSWORD: ${{secrets.APPSETTING_REDIS_PASSWORD}}
            APPSETTING_DISCORD_BOT_TOKEN: ${{secrets.APPSETTING_DISCORD_BOT_TOKEN}}
            APPSETTING_NOTIFICATION_CHANNELS: ${{secrets.APPSETTING_NOTIFICATION_CHANNELS}}
            APPSETTING_SPINBOARD_SENDGRID_API_KEY: ${{secrets.APPSETTING_SPINBOARD_SENDGRID_API_KEY}}
            APPSETTING_AUTH_TOKEN: ${{secrets.APPSETTING_AUTH_TOKEN}}
            APPSETTING_ALEXA_NOTIFY_ME_TOKEN: ${{secrets.APPSETTING_ALEXA_NOTIFY_ME_TOKEN}}
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_REGISTRY_USERNAME }}
          password: ${{ secrets.ACR_REGISTRY_PASSWORD }}
      - name: Clean up
        run: |
          docker builder prune -f
