name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: spinboard-java-main
  ACR_USERNAME: ${{ secrets.ACR_REGISTRY_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_REGISTRY_PASSWORD }}
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ACR_REGISTRY_USERNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            MAVEN_OPTS=${{ env.MAVEN_OPTS }}
            APPSETTING_COSMOS_DB: ${{secrets.APPSETTING_COSMOS_DB}}
            APPSETTING_REDIS_PORT: ${{secrets.APPSETTING_REDIS_PORT}}
            APPSETTING_REDIS_HOST: ${{secrets.APPSETTING_REDIS_HOST}}
            APPSETTING_COSMOS_URL: ${{secrets.APPSETTING_COSMOS_URL}}
            APPSETTING_COSMOS_KEY: ${{secrets.APPSETTING_COSMOS_KEY}}
            APPSETTING_REDIS_PASSWORD: ${{secrets.APPSETTING_REDIS_PASSWORD}}
            APPSETTING_DISCORD_BOT_TOKEN: ${{secrets.APPSETTING_DISCORD_BOT_TOKEN}}
            APPSETTING_NOTIFICATION_CHANNELS: ${{secrets.APPSETTING_NOTIFICATION_CHANNELS}}
            APPSETTING_SPINBOARD_SENDGRID_API_KEY: ${{secrets.APPSETTING_SPINBOARD_SENDGRID_API_KEY}}
            APPSETTING_AUTH_TOKEN: ${{secrets.APPSETTING_AUTH_TOKEN}}
            APPSETTING_ALEXA_NOTIFY_ME_TOKEN: ${{secrets.APPSETTING_ALEXA_NOTIFY_ME_TOKEN}}
          registry: ${{ env.ACR_REGISTRY_USERNAME }}.azurecr.io
          username: ${{ env.ACR_REGISTRY_USERNAME }}
          password: ${{ env.ACR_REGISTRY_PASSWORD }}
